### PR TITLE
Feature/add helpers translation

### PR DESCRIPTION
**Pull request by dingo-d**
Added translation strings to helpers description

### CODE REVIEW

**Comment by ernilambar** [comment]
@dingo-d What if we fix text domain after we rename plugin? :smile:

**Comment by dingo-d** [comment]
We'll have to redo everything again XD But since we are not yet sure on the plugin name...

**Comment by ernilambar** [comment]
We have finalized plugin name, no? `Theme Sniffer`? After @grappler completes review of https://github.com/WPTRT/ns-theme-check/pull/57 PR, we will rename the plugin.

**Comment by dingo-d** [comment]
Ok, I'll close this PR, and once that one comes through I'll fix that issue :)

**Pull request closed without merging**
